//
//  PegSolitaire.swift
//  wits
//
//  Classic peg solitaire. Every jump leaps one peg over a neighbour into an
//  empty hole and removes the jumped peg; clear the board down to one. Levels
//  are generated by reverse play — un-jumping k times from the final peg — so
//  every board is guaranteed solvable, never repeats, and carries an explicit
//  solution. Unlike the move-par puzzles, a solution is always pegs−1 jumps;
//  difficulty is planning depth (peg count and board), and quality is how far
//  you clear the board.
//

import SwiftUI

// MARK: - Engine

nonisolated struct PegMove: Equatable {
    let from: Int
    let over: Int
    let to: Int
}

nonisolated struct PegPuzzle: Equatable {
    let cols: Int
    let rows: Int
    let holes: Set<Int>
    var pegs: Set<Int>
    /// Required final hole (classic play); nil = last peg may end anywhere.
    let target: Int?
    /// Hex-lattice board: jumps run in 6 axial directions and rows render
    /// staggered; false = classic square lattice with 4 directions.
    var hex: Bool = false

    var isCleared: Bool { pegs.count == 1 }
    var isOnTarget: Bool { target.map { pegs == [$0] } ?? isCleared }
}

nonisolated struct PegSpec: Equatable {
    let shape: PegSolitaireEngine.Shape
    let pegs: Int
    let targetRequired: Bool
}

// Pure computation, generated off-main behind the board spinner.
nonisolated enum PegSolitaireEngine {
    enum Shape: CaseIterable {
        // square lattice (4 jump directions)
        case diamond13, square25, english33, european37, wiegleb45
        // hex lattice (6 axial jump directions; maps are axial coordinates,
        // rendered staggered — rows are right-aligned so a row's drawn centre
        // stays put as the stagger shifts it left)
        case triangle15, star13, trapezoid18, hexagon19

        var isHex: Bool {
            switch self {
            case .triangle15, .star13, .trapezoid18, .hexagon19: true
            default: false
            }
        }

        /// 'X' = hole, '.' = off-board.
        var map: [String] {
            switch self {
            case .diamond13:
                ["..X..",
                 ".XXX.",
                 "XXXXX",
                 ".XXX.",
                 "..X.."]
            case .square25:
                ["XXXXX",
                 "XXXXX",
                 "XXXXX",
                 "XXXXX",
                 "XXXXX"]
            case .english33:
                ["..XXX..",
                 "..XXX..",
                 "XXXXXXX",
                 "XXXXXXX",
                 "XXXXXXX",
                 "..XXX..",
                 "..XXX.."]
            case .european37:
                ["..XXX..",
                 ".XXXXX.",
                 "XXXXXXX",
                 "XXXXXXX",
                 "XXXXXXX",
                 ".XXXXX.",
                 "..XXX.."]
            case .wiegleb45:
                ["...XXX...",
                 "...XXX...",
                 "...XXX...",
                 "XXXXXXXXX",
                 "XXXXXXXXX",
                 "XXXXXXXXX",
                 "...XXX...",
                 "...XXX...",
                 "...XXX..."]
            case .triangle15:
                ["....X",
                 "...XX",
                 "..XXX",
                 ".XXXX",
                 "XXXXX"]
            case .star13:
                ["..X.X",
                 "..XX.",
                 "XXXXX",
                 ".XX..",
                 "X.X.."]
            case .trapezoid18:
                ["...XXX",
                 "..XXXX",
                 ".XXXXX",
                 "XXXXXX"]
            case .hexagon19:
                ["..XXX",
                 ".XXXX",
                 "XXXXX",
                 "XXXX.",
                 "XXX.."]
            }
        }

        var parsed: (cols: Int, rows: Int, holes: Set<Int>, center: Int) {
            let rows = map
            let cols = rows[0].count
            var holes: Set<Int> = []
            for (y, row) in rows.enumerated() {
                for (x, ch) in row.enumerated() where ch == "X" {
                    holes.insert(y * cols + x)
                }
            }
            // The hole nearest the drawn centroid (hex stagger included), so
            // every shape has a sensible marked-target hole.
            let stagger = isHex ? 0.5 : 0.0
            let points = holes.map { hole -> (Int, Double, Double) in
                let (x, y) = (hole % cols, hole / cols)
                return (hole, Double(x) + stagger * Double(y), Double(y))
            }
            let cx = points.map(\.1).reduce(0, +) / Double(points.count)
            let cy = points.map(\.2).reduce(0, +) / Double(points.count)
            let center = points.min { lhs, rhs in
                let l = (lhs.1 - cx) * (lhs.1 - cx) + (lhs.2 - cy) * (lhs.2 - cy)
                let r = (rhs.1 - cx) * (rhs.1 - cx) + (rhs.2 - cy) * (rhs.2 - cy)
                return l < r
            }!.0
            return (cols, rows.count, holes, center)
        }
    }

    private static func dirs(hex: Bool) -> [(Int, Int)] {
        hex ? [(1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1)]
            : [(1, 0), (-1, 0), (0, 1), (0, -1)]
    }

    /// All forward jumps available from a position.
    static func legalMoves(_ p: PegPuzzle) -> [PegMove] {
        var moves: [PegMove] = []
        for peg in p.pegs {
            let (x, y) = (peg % p.cols, peg / p.cols)
            for (dx, dy) in dirs(hex: p.hex) {
                let (ox, oy) = (x + dx, y + dy)
                let (tx, ty) = (x + 2 * dx, y + 2 * dy)
                guard tx >= 0, ty >= 0, tx < p.cols, ty < p.rows else { continue }
                let over = oy * p.cols + ox
                let to = ty * p.cols + tx
                guard p.pegs.contains(over), p.holes.contains(to), !p.pegs.contains(to) else { continue }
                moves.append(PegMove(from: peg, over: over, to: to))
            }
        }
        return moves
    }

    static func apply(_ move: PegMove, to p: inout PegPuzzle) {
        p.pegs.remove(move.from)
        p.pegs.remove(move.over)
        p.pegs.insert(move.to)
    }

    /// Reverse options: forward jumps whose *result* is the current position.
    /// Un-jumping peg q back along direction d needs two empty holes behind it.
    private static func reverseOptions(_ p: PegPuzzle) -> [PegMove] {
        var options: [PegMove] = []
        for peg in p.pegs {
            let (x, y) = (peg % p.cols, peg / p.cols)
            for (dx, dy) in dirs(hex: p.hex) {
                let (ox, oy) = (x - dx, y - dy)
                let (fx, fy) = (x - 2 * dx, y - 2 * dy)
                guard fx >= 0, fy >= 0, fx < p.cols, fy < p.rows else { continue }
                let over = oy * p.cols + ox
                let from = fy * p.cols + fx
                guard p.holes.contains(over), !p.pegs.contains(over),
                      p.holes.contains(from), !p.pegs.contains(from) else { continue }
                options.append(PegMove(from: from, over: over, to: peg))
            }
        }
        return options
    }

    // MARK: Level ladder

    /// Frozen exam spec per map level (1...40). The board shape changes every
    /// few levels (the classic solitaire-collection feel), alternating square
    /// and hex lattices while the peg count — planning depth — keeps ramping;
    /// the last bands add the classic "finish on the marked hole" rule.
    /// Near-full boards (the literal classic 32-peg game) stay out of the
    /// ladder — blind reverse search can't fill the final holes.
    static func spec(forMapLevel level: Int) -> PegSpec {
        let n = min(max(level, 1), 40)
        switch n {
        case ...4:
            return PegSpec(shape: .diamond13, pegs: 3 + n, targetRequired: false)                 // 4...7
        case ...8:
            return PegSpec(shape: .triangle15, pegs: 6 + (n - 5), targetRequired: false)          // 6...9
        case ...12:
            return PegSpec(shape: .star13, pegs: 7 + (n - 9), targetRequired: false)              // 7...10
        case ...16:
            return PegSpec(shape: .trapezoid18, pegs: 9 + (n - 13), targetRequired: false)        // 9...12
        case ...20:
            return PegSpec(shape: .hexagon19, pegs: 11 + (n - 17), targetRequired: false)         // 11...14
        case ...24:
            return PegSpec(shape: .square25, pegs: 13 + (n - 21), targetRequired: false)          // 13...16
        case ...28:
            return PegSpec(shape: .english33, pegs: 15 + (n - 25), targetRequired: false)         // 15...18
        case ...31:
            return PegSpec(shape: .european37, pegs: 19 + (n - 29), targetRequired: false)        // 19...21
        case ...35:
            return PegSpec(shape: .english33, pegs: 21 + (n - 32), targetRequired: true)          // 21...24
        default:
            return PegSpec(shape: .wiegleb45, pegs: 24 + (n - 36), targetRequired: true)          // 24...28
        }
    }

    /// Generate a board by un-jumping `spec.pegs - 1` times from the final
    /// peg. The recorded forward moves (reversed) are an explicit solution,
    /// so solvability is guaranteed by construction. A straight random walk
    /// dead-ends around 28–30 pegs on the full board, so the fill is a
    /// randomized DFS with backtracking — dense targets (the classic 32-peg
    /// game) stay reachable.
    static func generate(mapLevel: Int, attempts: Int = 12) -> (puzzle: PegPuzzle, solution: [PegMove]) {
        let spec = spec(forMapLevel: mapLevel)
        let board = spec.shape.parsed
        // Degrade the peg target rather than fail: a slightly easier board
        // beats no board, and small fills always succeed.
        var want = spec.pegs
        while want > 2 {
            for _ in 0..<attempts {
                let goal = spec.targetRequired ? board.center : board.holes.randomElement()!
                var puzzle = PegPuzzle(cols: board.cols, rows: board.rows, holes: board.holes,
                                       pegs: [goal], target: spec.targetRequired ? goal : nil,
                                       hex: spec.shape.isHex)
                var forward: [PegMove] = []
                var budget = 150_000
                if reverseFill(&puzzle, forward: &forward, target: want, budget: &budget) {
                    return (puzzle, forward.reversed())
                }
            }
            want -= 1
        }
        // Unreachable: two-peg fills always succeed on these shapes.
        let goal = board.center
        var puzzle = PegPuzzle(cols: board.cols, rows: board.rows, holes: board.holes,
                               pegs: [goal], target: nil, hex: spec.shape.isHex)
        var forward: [PegMove] = []
        var budget = 1_000
        _ = reverseFill(&puzzle, forward: &forward, target: 2, budget: &budget)
        return (puzzle, forward.reversed())
    }

    /// Randomized depth-first reverse fill: un-jump until `target` pegs are
    /// on the board, backtracking out of dead ends. Budget bounds the node
    /// count so a pathological seed can't stall the UI.
    private static func reverseFill(_ puzzle: inout PegPuzzle, forward: inout [PegMove],
                                    target: Int, budget: inout Int) -> Bool {
        if puzzle.pegs.count == target { return true }
        guard budget > 0 else { return false }
        for pick in reverseOptions(puzzle).shuffled() {
            budget -= 1
            puzzle.pegs.remove(pick.to)
            puzzle.pegs.insert(pick.over)
            puzzle.pegs.insert(pick.from)
            forward.append(pick)
            if reverseFill(&puzzle, forward: &forward, target: target, budget: &budget) { return true }
            puzzle.pegs.remove(pick.over)
            puzzle.pegs.remove(pick.from)
            puzzle.pegs.insert(pick.to)
            forward.removeLast()
            if budget <= 0 { return false }
        }
        return false
    }
}

// MARK: - Screen

struct PegSolitaireScreen: View {
    var cfg: GameConfig
    var onResult: (GameResult) -> Void

    /// Placeholder until the generator (run off-main; top levels can take a
    /// second) delivers the real board.
    @State private var puzzle = PegPuzzle(cols: 1, rows: 1, holes: [0], pegs: [0], target: nil)
    @State private var ready = false
    @State private var startPegs = 2
    @State private var parSeconds = 30.0
    @State private var selected: Int?
    @State private var history: [PegPuzzle] = []
    @State private var undos = 0
    @State private var elapsed = 0.0
    @State private var timerStartedAt = Date()
    @State private var hint = "tap a peg, then the empty hole two spaces away"
    @State private var vanishing: Int?
    @State private var finished = false

    private let startedAt = Date()
    private let level: Double
    private let mapLevel: Int
    private var world: GameWorld { GameID.pegSolitaire.world }

    init(cfg: GameConfig, onResult: @escaping (GameResult) -> Void) {
        self.cfg = cfg
        self.onResult = onResult
        self.level = cfg.difficulty.level
        self.mapLevel = cfg.mapLevel ?? DifficultyScale.contentLevel(for: .pegSolitaire,
                                                                     legacyDifficulty: cfg.difficulty.level)
    }

    private var pegsLeft: Int { puzzle.pegs.count }
    private var cleared: Int { startPegs - pegsLeft }
    private var legalDestinations: Set<Int> {
        guard let selected else { return [] }
        return Set(PegSolitaireEngine.legalMoves(puzzle).filter { $0.from == selected }.map(\.to))
    }

    var body: some View {
        GeometryReader { geo in
            ZStack {
                GameStageBackground(game: .pegSolitaire)
                if !ready {
                    VStack(spacing: 14) {
                        ProgressView()
                            .tint(.white)
                        Text("setting up the board…")
                            .font(.system(size: 14, weight: .semibold, design: world.bodyDesign))
                            .foregroundStyle(.white.opacity(0.7))
                    }
                } else {
                VStack(spacing: 0) {
                    topBar
                        .padding(.top, 8)
                        .padding(.horizontal, WitsMetrics.screenPadding)

                    Spacer(minLength: 24)

                    Text(hint)
                        .font(.system(size: 16, weight: .heavy, design: .rounded))
                        .foregroundStyle(.white)
                        .multilineTextAlignment(.center)
                        .lineLimit(2)
                        .minimumScaleFactor(0.72)
                        .padding(.horizontal, 18)
                        .padding(.vertical, 12)
                        .frame(maxWidth: .infinity)
                        .background(Color.black.opacity(0.22), in: RoundedRectangle(cornerRadius: 8, style: .continuous))
                        .padding(.horizontal, WitsMetrics.screenPadding)
                        .opacity(hint.isEmpty ? 0 : 1)
                        .animation(.easeOut(duration: 0.18), value: hint)

                    boardView(in: geo.size)
                        .padding(.top, 18)

                    Spacer(minLength: 24)

                    progressStrip
                        .padding(.horizontal, WitsMetrics.screenPadding)
                        .padding(.bottom, 12)
                }
                }
            }
        }
        .task { await setUpAndRun() }
        .accessibilityElement(children: .contain)
        .accessibilityLabel("Peg solitaire")
    }

    private var topBar: some View {
        HStack(spacing: 10) {
            Spacer()
                .frame(width: 38)

            HStack(spacing: 16) {
                Text(Self.clock(elapsed))
                    .font(.system(size: 17, weight: .heavy, design: .rounded))
                    .monospacedDigit()
                    .frame(minWidth: 66, alignment: .leading)
                Spacer(minLength: 0)
                Text("pegs: \(pegsLeft)")
                    .font(.system(size: 17, weight: .semibold, design: .rounded))
                    .monospacedDigit()
            }
            .foregroundStyle(.white)
            .padding(.horizontal, 18)
            .frame(height: 42)
            .background(Color.black.opacity(0.35), in: Capsule())

            Button {
                undo()
            } label: {
                Image(systemName: "arrow.uturn.backward")
                    .font(.system(size: 17, weight: .heavy))
                    .foregroundStyle(.white.opacity(history.isEmpty ? 0.35 : 1))
                    .frame(width: 48, height: 48)
                    .background(.white.opacity(0.18), in: Circle())
            }
            .buttonStyle(.plain)
            .disabled(history.isEmpty || finished)
            .accessibilityLabel("Undo last jump")

            Button {
                showHelp()
            } label: {
                Image(systemName: "questionmark")
                    .font(.system(size: 20, weight: .heavy))
                    .foregroundStyle(.white)
                    .frame(width: 48, height: 48)
                    .background(.white.opacity(0.18), in: Circle())
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Show rule reminder")
        }
    }

    private var progressStrip: some View {
        VStack(spacing: 8) {
            HStack {
                Label(puzzle.target != nil ? "finish on the ring" : "finish anywhere",
                      systemImage: "circle.grid.cross.fill")
                Spacer()
                Text("cleared \(cleared)/\(startPegs - 1)")
            }
            .font(.system(size: 13, weight: .heavy, design: .rounded))
            .foregroundStyle(.white.opacity(0.78))

            ProgressView(value: min(1, Double(cleared) / Double(max(1, startPegs - 1))))
                .tint(world.accent)
                .background(.white.opacity(0.16), in: Capsule())
        }
    }

    // MARK: Board

    private func boardView(in size: CGSize) -> some View {
        let inset: CGFloat = 12
        let maxW = size.width - 36
        let maxH = size.height * 0.54
        // Hex boards stagger each row by half a cell and pack rows at the
        // triangular-lattice height; drawn X spans differ from the raw grid,
        // so lay out from the actual drawn positions.
        let stagger: CGFloat = puzzle.hex ? 0.5 : 0
        let drawnX = puzzle.holes.map { CGFloat($0 % puzzle.cols) + stagger * CGFloat($0 / puzzle.cols) }
        let drawnY = puzzle.holes.map { CGFloat($0 / puzzle.cols) }
        let minX = drawnX.min() ?? 0, spanX = (drawnX.max() ?? 0) - minX + 1
        let minY = drawnY.min() ?? 0, spanY = (drawnY.max() ?? 0) - minY + 1
        let rowH: CGFloat = puzzle.hex ? 0.87 : 1
        let cell = min((maxW - inset * 2) / spanX,
                       (maxH - inset * 2) / (spanY * rowH))
        let boardW = cell * spanX + inset * 2
        let boardH = cell * spanY * rowH + inset * 2
        let destinations = legalDestinations

        return ZStack(alignment: .topLeading) {
            RoundedRectangle(cornerRadius: 7, style: .continuous)
                .fill(world.surface.opacity(0.90))

            ForEach(puzzle.holes.sorted(), id: \.self) { hole in
                let gx = CGFloat(hole % puzzle.cols) + stagger * CGFloat(hole / puzzle.cols)
                let x = inset + (gx - minX) * cell + cell / 2
                let y = inset + (CGFloat(hole / puzzle.cols) - minY) * cell * rowH + cell / 2
                holeView(hole, cell: cell, isDestination: destinations.contains(hole))
                    .position(x: x, y: y)
                    .onTapGesture { tap(hole) }
            }
        }
        .frame(width: boardW, height: boardH)
        .animation(.spring(response: 0.24, dampingFraction: 0.85), value: puzzle.pegs)
        .animation(.easeOut(duration: 0.15), value: selected)
    }

    @ViewBuilder
    private func holeView(_ hole: Int, cell: CGFloat, isDestination: Bool) -> some View {
        let hasPeg = puzzle.pegs.contains(hole)
        let isSelected = selected == hole
        let isTarget = puzzle.target == hole

        ZStack {
            Circle()
                .fill(Color.black.opacity(0.32))
                .frame(width: cell * 0.72, height: cell * 0.72)
            if isTarget && !hasPeg {
                Circle()
                    .strokeBorder(world.accent.opacity(0.9), lineWidth: 2.5)
                    .frame(width: cell * 0.72, height: cell * 0.72)
            }
            if isDestination {
                Circle()
                    .strokeBorder(Color.white.opacity(0.85), style: StrokeStyle(lineWidth: 2.5, dash: [5, 4]))
                    .frame(width: cell * 0.84, height: cell * 0.84)
            }
            if hasPeg {
                Circle()
                    .fill(isSelected ? world.secondary : world.ink)
                    .frame(width: cell * 0.58, height: cell * 0.58)
                    .scaleEffect(vanishing == hole ? 0.1 : (isSelected ? 1.12 : 1))
                    .shadow(color: .black.opacity(0.25), radius: 3, y: 2)
            }
        }
        .contentShape(Circle().scale(1.3))
        .accessibilityLabel(hasPeg ? "Peg" : "Empty hole")
    }

    // MARK: Play

    private func tap(_ hole: Int) {
        guard !finished else { return }
        if puzzle.pegs.contains(hole) {
            selected = selected == hole ? nil : hole
            hint = ""
            return
        }
        guard let from = selected,
              let move = PegSolitaireEngine.legalMoves(puzzle).first(where: { $0.from == from && $0.to == hole }) else {
            if selected != nil {
                hint = "a jump lands two spaces away, straight over a peg"
                cfg.report(.nearMiss)
            }
            return
        }
        history.append(puzzle)
        vanishing = move.over
        withAnimation(.spring(response: 0.24, dampingFraction: 0.85)) {
            PegSolitaireEngine.apply(move, to: &puzzle)
        }
        selected = nil
        vanishing = nil
        hint = ""
        GameFeel.shared.play(.correct(combo: max(1, min(6, cleared / 3))))
        checkEnd()
    }

    private func undo() {
        guard let last = history.popLast(), !finished else { return }
        undos += 1
        selected = nil
        withAnimation(.spring(response: 0.24, dampingFraction: 0.85)) {
            puzzle = last
        }
    }

    private func checkEnd() {
        guard PegSolitaireEngine.legalMoves(puzzle).isEmpty else { return }
        finished = true
        if puzzle.isCleared {
            hint = puzzle.isOnTarget ? "cleared!" : "cleared — off the ring"
            GameFeel.shared.play(.newBest)
        } else {
            hint = "no jumps left — \(pegsLeft) pegs stranded"
            cfg.report(.miss)
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.9) {
            finish()
        }
    }

    private func finish() {
        let seconds = max(1, elapsed)
        let clear = Double(cleared) / Double(max(1, startPegs - 1))
        let timeEfficiency = min(1, parSeconds / seconds)
        let accuracy = PegSolitairePolicy.quality(clear: clear,
                                                  timeEfficiency: timeEfficiency,
                                                  solved: puzzle.isCleared,
                                                  onTarget: puzzle.isOnTarget,
                                                  undos: Double(undos))
        let score = max(0, Int((Double(cleared) * 45
            + (puzzle.isCleared ? 400 : 0)
            + timeEfficiency * 300).rounded()))

        var result = GameResult(game: .pegSolitaire, score: score, accuracy: accuracy)
        result.trials = cleared
        result.startedAt = startedAt
        result.durationMs = Int(seconds * 1000)
        result.raw = [
            "startPegs": Double(startPegs),
            "endPegs": Double(pegsLeft),
            "cleared": Double(cleared),
            "clearPct": (clear * 100).rounded(),
            "solved": puzzle.isCleared ? 1 : 0,
            "onTarget": puzzle.isOnTarget ? 1 : 0,
            "undos": Double(undos),
            "seconds": seconds.rounded(),
            "parSeconds": parSeconds.rounded(),
            "pegLevel": level
        ]
        onResult(result)
    }

    private func showHelp() {
        hint = puzzle.target != nil
            ? "jump pegs to remove them. the last peg must land on the ringed hole"
            : "jump pegs to remove them until a single peg remains"
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.2) {
            if !finished {
                hint = ""
            }
        }
    }

    private func setUpAndRun() async {
        if !ready {
            let target = mapLevel
            let generated = await Task.detached(priority: .userInitiated) {
                PegSolitaireEngine.generate(mapLevel: target)
            }.value
            puzzle = generated.puzzle
            startPegs = generated.puzzle.pegs.count
            // Planning time per jump is generous by design — the dominant
            // quality term is how far the board gets cleared.
            parSeconds = Double(startPegs) * 7 + 20
            ready = true
            timerStartedAt = Date()
        }
        while !Task.isCancelled {
            try? await Task.sleep(for: .milliseconds(250))
            guard !finished else { return }
            elapsed = cfg.activeElapsed(since: timerStartedAt)
        }
    }

    private static func clock(_ seconds: Double) -> String {
        let total = Int(seconds.rounded(.down))
        return String(format: "%02d:%02d", total / 60, total % 60)
    }
}
